#!/bin/bash
### shell du job
#$ -S /bin/bash
### nom du job (a changer)
#$ -N MRDR_vs_hybrid_3
### file d'attente (a changer)
#$ -q monointeldeb128
### charger l'environnement utilisateur pour SGE
#$ -cwd
### exporter les variables d'environnement sur tous les noeuds d'execution
#$ -V
### mails en debut et fin d'execution
#$ -m be

# aller dans le repertoire de travail/soumission
# important, sinon, le programme est lancé depuis ~/
cd ${SGE_O_WORKDIR}

### configurer l'environnement
source /usr/share/lmod/lmod/init/bash
module load GCC/6.4.0/Bowtie2/2.3.3

### execution du programme
###EXECDIR=${HOME}/Formations/Sequentiel
###${EXECDIR}/SommeVecVecSEQ.exe < Monfichierdedata > monfichierresultat

bowtie2-build /scratch/lestrada/stage_mbelari/results/hybrid_test/full_test/test3/MinLen500-0-001/consensus_dir/final_assembly.fasta hybrid_index_3

bowtie2 --very-sensitive  -x hybrid_index -U /scratch/lestrada/stage_mbelari/data/raw/2017_09_13_MRDR5_trim_Mbelari_mapped_sort.fastq.gz -S 2018-06-08-MRDR5_vs_Hybrid_assembly.sam

bowtie2 --very-sensitive -x hybrid_index -U /scratch/lestrada/stage_mbelari/data/raw/2017_09_13_MRDR6_trim_Mbelari_mapped_sort.fastq.gz -S 2018-06-08-MRDR6_vs_Hybrid_assembly.sam

samtools view -Sb 2018-06-08-MRDR5_vs_Hybrid_assembly.sam > 2018-06-08-MRDR5_vs_Hybrid_assembly.bam

samtools view -Sb 2018-06-08-MRDR6_vs_Hybrid_assembly.sam > 2018-06-08-MRDR6_vs_Hybrid_assembly.bam

samtools sort 2018-06-08-MRDR5_vs_Hybrid_assembly.bam -o 2018-06-08-MRDR5_vs_Hybrid_assembly.sorted.bam

samtools sort 2018-06-08-MRDR6_vs_Hybrid_assembly.bam -o 2018-06-08-MRDR6_vs_Hybrid_assembly.sorted.bam

samtools index 2018-06-08-MRDR5_vs_Hybrid_assembly.sorted.bam

samtools index 2018-06-08-MRDR6_vs_Hybrid_assembly.sorted.bam


# fin```

