 SGE
### shell du job
#$ -S /bin/bash
### nom du job (a changer)
#$ -N CanuTest
### file d'attente (a changer)
#$ -q monointeldeb128
### charger l'environnement utilisateur pour SGE
#$ -cwd
### exporter les variables d'environnement sur tous les noeuds d'execution
#$ -V
### mails en debut et fin d'execution
#$ -m be

# aller dans le repertoire de travail/soumission
# important, sinon, le programme est lancé depuis ~/
cd ${SGE_O_WORKDIR}

### configurer l'environnement
source /usr/share/modules/init/bash
module use ~/privatemodules
ml canu/1.7

### execution du programme
###EXECDIR=${HOME}/Formations/Sequentiel
###${EXECDIR}/SommeVecVecSEQ.exe < Monfichierdedata > monfichierresultat
canu -p 2018-05-17-testMBELA01182 -d 2018-05-17-testMBELA01182 genomeSize=57k useGrid=false -nanopore-raw Canu_tests/data/2018-05-17-MBELA01182_nanopore_reads_subset.fastq

# fin```
